################################
#                    VelocityPteroPower             #
#                       by TubYoub                        #
################################

# Version of the configuration file
fileversion: 1

# Check for updates
# If true, the plugin will check for updates on startup.
# If a new version is available, a message will be sent to the console and to players with the permission "ptero.reload".
checkUpdate: true

# This is used to check the server status to transfer players after the server starts
startupJoin:
  # Once the server is pingable, wait the specified amount of seconds before sending the player to the server
  # This is useful to wait for plugins like Luckperms to fully load
  # If you set it to 0, the player will be connected as soon as the server is pingable
  joinDelay: 5

# Pterodactyl configuration
pterodactyl:
  # The URL of your pterodactyl panel
  # If you use Cloudflare Tunnel, you need to allow the ip in the bypass setting.
  url: "https://panel.example.com"
  # The client api key of your pterodactyl panel. It starts with "ptlc_".
  # You can find the client api key in the "API Credentials" tab of the "Account" page.
  apiKey: "ptlc_000000000000000000000000000000000000000000"

# Per server configuration
# Make sure that the server names match the registered servers in the velocity.toml
servers:
  #server name
  example:

    # Pterodactyl server ID
    # You can find the Pterodactyl server ID in the URL of the server page.
    # For example, if the URL is https://panel.example.com/server/1234abcd, the server ID is 1234abcd.

    id: 1234abcd

    # The time in seconds to stop the server after the last player leaves.
    # If you don't want to stop the server automatically, set it to -1.
    # If you set it to 0, the server will be stopped immediately after the last player leaves.

    timeout: 30
    startupJoinDelay: 30