id: velocity-ptero-power
name: VelocityPteroPower
version: 1.0
main: com.example.velocitypteropower.VelocityPteroPower
description: A Velocity plugin for managing servers with the Pterodactyl Panel.
authors:
  - TubYoub
commands:
  ptero:
    description: Manage servers with the Pterodactyl Panel
    usage: /<command> <start|stop|reload> [serverName]